<a href="https://colab.research.google.com/github/aps0611/Capegimini-Data-Hackathon/blob/aps0611/book1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

pd.set_option('display.max_columns', None)

# The major crops selected in this model are:

`corn cotton and sorghum`

In [2]:
df_cotton = pd.read_csv("https://raw.githubusercontent.com/aps0611/Capegimini-Data-Hackathon/aps0611/dataset/Texas/crops/cotton_1.csv")
df_cotton.head(5)

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,"6,261.00",17
1,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,"6,243.00",17
2,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,840.00,17
3,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,NaN,(D)
4,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,NaN,(D)

In [3]:
df_cotton.shape

(174, 21)

In [4]:
df_cotton['COTTON-AREA-ACRES'] = df_cotton['Value']
df_cotton.head()

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%),COTTON-AREA-ACRES
0,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,"6,261.00",17,"6,261.00"
1,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,"6,243.00",17,"6,243.00"
2,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,840.00,17,840.00
3,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,NaN,(D),NaN
4,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,NaN,0,NaN,COTTON,COTTON - ACRES HARVESTED,TOTAL,NOT SPECIFIED,NaN,(D),NaN

In [5]:
df_cotton.drop(['Program','Region','Commodity','Zip Code', 'CV (%)','Year', 
               'Period', 'Week Ending', 'watershed_code', 'Watershed','Data Item',
               'Domain', 'Domain Category', 'Value'], 
              inplace = True,
              axis = 'columns')
df_cotton.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,"6,261.00"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,"6,243.00"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,840.00

In [6]:
len(df_cotton['County'].unique())

174

# Corn

In [7]:
df_corn = pd.read_csv('https://raw.githubusercontent.com/aps0611/Capegimini-Data-Hackathon/aps0611/dataset/Texas/crops/corn_1.csv')

In [8]:
df_corn.head(5)

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"67,409.00",24.2
1,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"3,965.00",24.2
2,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"22,840.00",24.2
3,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"3,002.00",24.2
4,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"1,657.00",24.2

In [9]:
df_corn.shape

(176, 21)

In [10]:
df_corn.rename(columns = {'Value': 'CORN-GRAIN-ACRES'}, inplace = True)
df_corn.head(5)

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,CORN-GRAIN-ACRES,CV (%)
0,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"67,409.00",24.2
1,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"3,965.00",24.2
2,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"22,840.00",24.2
3,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"3,002.00",24.2
4,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"1,657.00",24.2

In [11]:
df_corn.drop(['Program','Region','Commodity','Zip Code', 'CV (%)','Year', 
               'Period', 'Week Ending', 'watershed_code', 'Watershed','Data Item',
               'Domain', 'Domain Category'], inplace = True, axis = 'columns')
df_corn

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,CORN-GRAIN-ACRES
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,"67,409.00"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,"3,965.00"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,"22,840.00"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,"3,002.00"
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,"1,657.00"
...,...,...,...,...,...,...,...,...
171,COUNTY,TEXAS,48,UPPER COAST,90,LIBERTY,291,NaN
172,COUNTY,TEXAS,48,UPPER COAST,90,MATAGORDA,321,"32,924.00"
173,COUNTY,TEXAS,48,UPPER COAST,90,ORANGE,361,6.00
174,COUNTY,TEXAS,48,UPPER COAST,90,VICTORIA,469,"25,023.00"
175,COUNTY,TEXAS,48,UPPER COAST,90,WHARTON,481,"69,499.00"

In [12]:
# combine the two dataframes
df_combined = pd.merge(df_cotton, df_corn, on = ['Geo Level','State','State ANSI','Ag District',
                                                'Ag District Code','County','County ANSI'], how = 'outer')
df_combined

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,"6,261.00","67,409.00"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,"6,243.00","3,965.00"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,840.00,"22,840.00"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,"3,002.00"
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,"1,657.00"
...,...,...,...,...,...,...,...,...,...
204,COUNTY,TEXAS,48,SOUTH TEXAS,96,LA SALLE,283,NaN,NaN
205,COUNTY,TEXAS,48,SOUTH TEXAS,96,MCMULLEN,311,NaN,"1,500.00"
206,COUNTY,TEXAS,48,UPPER COAST,90,CHAMBERS,71,NaN,NaN
207,COUNTY,TEXAS,48,UPPER COAST,90,LIBERTY,291,NaN,NaN
208,COUNTY,TEXAS,48,UPPER COAST,90,ORANGE,361,NaN,6.00

# Sorghum

In [13]:
df_sorghum = pd.read_csv('https://raw.githubusercontent.com/aps0611/Capegimini-Data-Hackathon/aps0611/dataset/Texas/crops/sorghum_1.csv')
df_sorghum.head(3)

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,NaN,NaN,0,NaN,SORGHUM,"SORGHUM, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"7,264.00",18.3
1,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,NaN,NaN,0,NaN,SORGHUM,"SORGHUM, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"1,299.00",18.3
2,CENSUS,2017,YEAR,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,NaN,NaN,0,NaN,SORGHUM,"SORGHUM, GRAIN - ACRES HARVESTED",TOTAL,NOT SPECIFIED,"7,102.00",18.3

In [14]:
df_sorghum.drop(['Program','Region','Commodity','Zip Code', 'CV (%)','Year', 
               'Period', 'Week Ending', 'watershed_code', 'Watershed','Data Item',
               'Domain', 'Domain Category'], inplace = True, axis = 'columns')

In [15]:
df_sorghum.rename(columns = {'Value': 'SORGHUM-ACRES'}, inplace = True)
df_sorghum.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,SORGHUM-ACRES
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,"7,264.00"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,"1,299.00"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,"7,102.00"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,"4,870.00"
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,"4,705.00"

In [16]:
df_combined = pd.merge(df_combined, df_sorghum, on = ['Geo Level','State','State ANSI','Ag District',
                                                'Ag District Code','County','County ANSI'], how = 'outer')
df_combined

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27,"6,261.00","67,409.00","7,264.00"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35,"6,243.00","3,965.00","1,299.00"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85,840.00,"22,840.00","7,102.00"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97,NaN,"3,002.00","4,870.00"
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99,NaN,"1,657.00","4,705.00"
...,...,...,...,...,...,...,...,...,...,...
208,COUNTY,TEXAS,48,UPPER COAST,90,ORANGE,361,NaN,6.00,NaN
209,COUNTY,TEXAS,48,CROSS TIMBERS,30,MONTAGUE,337,NaN,NaN,NaN
210,COUNTY,TEXAS,48,CROSS TIMBERS,30,STEPHENS,429,NaN,NaN,300.00
211,COUNTY,TEXAS,48,SOUTH TEXAS,96,DUVAL,131,NaN,NaN,NaN
212,COUNTY,TEXAS,48,UPPER COAST,90,JEFFERSON,245,NaN,NaN,NaN

# Cattle:

In [17]:
df_cattle = pd.read_csv('https://raw.githubusercontent.com/aps0611/Capegimini-Data-Hackathon/aps0611/dataset/Texas/Livestock/cattle.csv')
df_cattle.head(3)

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Zip Code,Region,watershed_code,Watershed,Commodity,Domain,Domain Category,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, BEEF - INVENTORY - <b>CV (%)</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>CV (%)</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>CV (%)</b>"
0,SURVEY,2022,FIRST OF JAN,NaN,COUNTY,TEXAS,48,NaN,99,OTHER COUNTIES,NaN,NaN,NaN,0,NaN,CATTLE,TOTAL,NOT SPECIFIED,"1,274,000",NaN,"57,300",NaN,NaN,NaN
1,SURVEY,2022,FIRST OF JAN,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,NaN,NaN,0,NaN,CATTLE,TOTAL,NOT SPECIFIED,(D),NaN,(D),NaN,"37,000",NaN
2,SURVEY,2022,FIRST OF JAN,NaN,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,NaN,NaN,0,NaN,CATTLE,TOTAL,NOT SPECIFIED,"23,500",NaN,NaN,NaN,"52,000",NaN

In [18]:
df_cattle = df_cattle[['Geo Level', 'State', 'State ANSI', 'Ag District', 'Ag District Code',
       'County', 'County ANSI',
       'CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>'
       ]]

In [19]:
df_cattle.columns

Index(['Geo Level', 'State', 'State ANSI', 'Ag District', 'Ag District Code',
       'County', 'County ANSI',
       'CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>'],
      dtype='object')

In [20]:
df_cattle

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>"
0,COUNTY,TEXAS,48,NaN,99,OTHER COUNTIES,NaN,"1,274,000","57,300",NaN
1,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,(D),(D),"37,000"
2,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"23,500",NaN,"52,000"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,"17,400",NaN,"42,000"
4,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,(D),(D),"86,000"
...,...,...,...,...,...,...,...,...,...,...
250,COUNTY,TEXAS,48,UPPER COAST,90,LIBERTY,291.0,"29,500",NaN,"48,000"
251,COUNTY,TEXAS,48,UPPER COAST,90,MATAGORDA,321.0,"33,000",NaN,"54,000"
252,COUNTY,TEXAS,48,UPPER COAST,90,ORANGE,361.0,"6,000",NaN,"9,900"
253,COUNTY,TEXAS,48,UPPER COAST,90,VICTORIA,469.0,"30,500",NaN,"49,500"
254,COUNTY,TEXAS,48,UPPER COAST,90,WHARTON,481.0,(D),(D),"58,000"

In [21]:
df_combined = pd.merge(df_combined, df_cattle, on = ['Geo Level','State','State ANSI','Ag District',
                                                'Ag District Code','County','County ANSI'], how = 'outer')
df_combined

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>"
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",(D),(D),"37,000"
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00","23,500",NaN,"52,000"
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00","17,400",NaN,"42,000"
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,"3,002.00","4,870.00",(D),(D),"86,000"
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,"1,657.00","4,705.00","25,500",NaN,"55,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,COUNTY,TEXAS,48,TRANS-PECOS,60,PRESIDIO,377.0,NaN,NaN,NaN,"17,200",NaN,"28,000"
251,COUNTY,TEXAS,48,TRANS-PECOS,60,TERRELL,443.0,NaN,NaN,NaN,"2,900",NaN,"5,100"
252,COUNTY,TEXAS,48,TRANS-PECOS,60,WARD,475.0,NaN,NaN,NaN,"2,200",NaN,"4,200"
253,COUNTY,TEXAS,48,TRANS-PECOS,60,WINKLER,495.0,NaN,NaN,NaN,"2,800",NaN,"6,200"
254,COUNTY,TEXAS,48,UPPER COAST,90,GALVESTON,167.0,NaN,NaN,NaN,"7,200",NaN,"10,500"

In [22]:
df_precipitation = pd.read_csv('https://raw.githubusercontent.com/aps0611/Capegimini-Data-Hackathon/aps0611/dataset/Texas/precipitation/precipitation.csv')
df_precipitation

,Rank,County,Mean Annual\nPrecipitation (in.),Mean Annual\nPrecipitation (cm.)
0,1,JASPER,60.57,153.8478
1,2,LIBERTY,60.52,153.7208
2,3,JEFFERSON,59.89,152.1206
3,4,ORANGE,59.00,149.8600
4,5,BRAZORIA,57.24,145.3896
...,...,...,...,...
250,251,HUDSPETH,11.93,30.3022
251,252,REEVES,11.61,29.4894
252,253,EL PASO,9.43,23.9522
253,254,LOVING,9.10,23.1140
254,Average,NaN,28.87,73.3298

In [23]:
df_combined = pd.merge(df_combined, df_precipitation, on = ['County'], how = 'inner')
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Rank,Mean Annual\nPrecipitation (in.),Mean Annual\nPrecipitation (cm.)
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",(D),(D),"37,000",89,35.81,90.9574
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00","23,500",NaN,"52,000",95,35.07,89.0778
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00","17,400",NaN,"42,000",61,41.01,104.1654

In [24]:
df_combined.drop(['Mean Annual\nPrecipitation (in.)','Rank'],inplace = True, axis = 'columns')
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.)
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",(D),(D),"37,000",90.9574
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00","23,500",NaN,"52,000",89.0778
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00","17,400",NaN,"42,000",104.1654

In [25]:
df_combined['Ag District'].unique()

array(['BLACKLANDS', 'COASTAL BEND', 'CROSS TIMBERS', 'EAST TEXAS NORTH',
       'EAST TEXAS SOUTH', 'EDWARDS PLATEAU', 'LOWER VALLEY',
       'NORTHERN HIGH PLAINS', 'NORTHERN LOW PLAINS', 'SOUTH CENTRAL',
       'SOUTH TEXAS', 'SOUTHERN HIGH PLAINS', 'SOUTHERN LOW PLAINS',
       'TRANS-PECOS', 'UPPER COAST'], dtype=object)

In [26]:
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.)
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",(D),(D),"37,000",90.9574
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00","23,500",NaN,"52,000",89.0778
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00","17,400",NaN,"42,000",104.1654

In [27]:
from geopy.geocoders import Nominatim

import matplotlib.pyplot as plt
%matplotlib inline

In [28]:
class FarmGeocoder:
    def __init__(self):
        self.geocoder = Nominatim(user_agent="FarmGeocoder")

    def geocode_address(self, address):
        location = self.geocoder.geocode(address)
        return (location.latitude, location.longitude) if location else None

# Get the farm address
farm_addresses = list(df_combined.County.unique())

geocoder = FarmGeocoder()

data = []
for address in farm_addresses:
    coordinates = geocoder.geocode_address(address + ',Texas')
    if coordinates:
        latitude, longitude = coordinates
        print(f"Address: {address}")
        print(f"Latitude: {latitude}")
        print(f"Longitude: {longitude}")
        print("---------")
        data.append({'County': address, 'Latitude': latitude, 'Longitude': longitude})
    else:
        print(f"Failed to geocode address: {address}")
        print("---------")

df_geolocation = pd.DataFrame(data)

Address: BELL
Latitude: 31.0081659
Longitude: -97.4314413
---------
Address: BOSQUE
Latitude: 31.8778358
Longitude: -97.6561014
---------
Address: COLLIN
Latitude: 33.1609629
Longitude: -96.6060984
---------
Address: COOKE
Latitude: 33.582486
Longitude: -97.2055298
---------
Address: CORYELL
Latitude: 31.3689333
Longitude: -97.8184077
---------
Address: DELTA
Latitude: 33.3926893
Longitude: -95.6749486
---------
Address: DENTON
Latitude: 33.1838787
Longitude: -97.1413417
---------
Address: ELLIS
Latitude: 32.3347829
Longitude: -96.7920233
---------
Address: FALLS
Latitude: 31.2320941
Longitude: -96.9262126
---------
Address: FANNIN
Latitude: 33.5372542
Longitude: -96.0902822
---------
Address: GRAYSON
Latitude: 33.5636114
Longitude: -96.6702111
---------
Address: HAMILTON
Latitude: 31.6429346
Longitude: -97.9715967
---------
Address: HILL
Latitude: 31.9595085
Longitude: -97.0881654
---------
Address: HUNT
Latitude: 33.1161567
Longitude: -96.0808922
---------
Address: JOHNSON
Latitude: 32.3766071
Longitude: -97.3568623
---------
Address: KAUFMAN
Latitude: 32.601641
Longitude: -96.3375126
---------
Address: LAMAR
Latitude: 33.6383552
Longitude: -95.582343
---------
Address: LIMESTONE
Latitude: 31.5261854
Longitude: -96.580617
---------
Address: MCLENNAN
Latitude: 31.5487691
Longitude: -97.2189254
---------
Address: MILAM
Latitude: 30.7626867
Longitude: -96.9981706
---------
Address: NAVARRO
Latitude: 32.0279525
Longitude: -96.4985456
---------
Address: ROCKWALL
Latitude: 32.8923464
Longitude: -96.4066987
---------
Address: WILLIAMSON
Latitude: 30.6580927
Longitude: -97.6041649
---------
Address: KLEBERG
Latitude: 27.3983129
Longitude: -97.7485096
---------
Address: NUECES
Latitude: 27.7153774
Longitude: -97.6199942
---------
Address: REFUGIO
Latitude: 28.3171012
Longitude: -97.2394101
---------
Address: SAN PATRICIO
Latitude: 28.0003594
Longitude: -97.50204408532724
---------
Address: ARCHER
Latitude: 33.5816594
Longitude: -98.7044869
---------
Address: BROWN
Latitude: 31.7525184
Longitude: -98.9904722
---------
Address: CALLAHAN
Latitude: 32.2810409
Longitude: -99.3612437
---------
Address: CLAY
Latitude: 33.6856157
Longitude: -98.2123296
---------
Address: COMANCHE
Latitude: 31.9130171
Longitude: -98.527388
---------
Address: EASTLAND
Latitude: 32.2978594
Longitude: -98.8630896
---------
Address: ERATH
Latitude: 32.1954856
Longitude: -98.2213499
---------
Address: PARKER
Latitude: 32.77725975
Longitude: -97.80455986920202
---------
Address: SHACKELFORD
Latitude: 32.7088752
Longitude: -99.3307616
---------
Address: THROCKMORTON
Latitude: 33.1571081
Longitude: -99.2017838
---------
Address: WISE
Latitude: 33.2139213
Longitude: -97.6563925
---------
Address: YOUNG
Latitude: 33.1508315
Longitude: -98.6962766
---------
Address: ANDERSON
Latitude: 31.7819242
Longitude: -95.6258199
---------
Address: BOWIE
Latitude: 33.4198886
Longitude: -94.4479626
---------
Address: FRANKLIN
Latitude: 33.2002659
Longitude: -95.2231752
---------
Address: HARRISON
Latitude: 32.5233959
Longitude: -94.3982158
---------
Address: HOPKINS
Latitude: 33.1368252
Longitude: -95.5656578
---------
Address: HOUSTON
Latitude: 29.7589382
Longitude: -95.3676974
---------
Address: BRAZOS
Latitude: 30.6993189
Longitude: -96.3497772
---------
Address: FREESTONE
Latitude: 31.6924428
Longitude: -96.1629601
---------
Address: GRIMES
Latitude: 30.5169334
Longitude: -95.9943034
---------
Address: MADISON
Latitude: 30.9551586
Longitude: -95.9507234
---------
Address: ROBERTSON
Latitude: 31.0339058
Longitude: -96.5079742
---------
Address: SAN JACINTO
Latitude: 30.5083577
Longitude: -95.1902362
---------
Address: WALKER
Latitude: 30.6795741
Longitude: -95.5522823
---------
Address: WALLER
Latitude: 29.9443902
Longitude: -95.9955885
---------
Address: BLANCO
Latitude: 30.2419274
Longitude: -98.4004594
---------
Address: BURNET
Latitude: 30.7763939
Longitude: -98.1700016
---------
Address: COKE
Latitude: 31.8695226
Longitude: -100.5474369
---------
Address: CONCHO
Latitude: 31.3102947
Longitude: -99.8507578
---------
Address: IRION
Latitude: 31.2931196
Longitude: -100.980073
---------
Address: KINNEY
Latitude: 29.326416
Longitude: -100.4165707
---------
Address: LLANO
Latitude: 30.6663312
Longitude: -98.6970374
---------
Address: MCCULLOCH
Latitude: 31.1699604
Longitude: -99.3885277
---------
Address: REAGAN
Latitude: 31.3458428
Longitude: -101.5295291
---------
Address: SAN SABA
Latitude: 31.122268
Longitude: -98.8397049
---------
Address: SCHLEICHER
Latitude: 30.8791222
Longitude: -100.5418961
---------
Address: TOM GREEN
Latitude: 31.3782559
Longitude: -100.4133839
---------
Address: UPTON
Latitude: 31.3720387
Longitude: -102.0386055
---------
Address: UVALDE
Latitude: 29.300357
Longitude: -99.7733181
---------
Address: CAMERON
Latitude: 26.1291189
Longitude: -97.4134281
---------
Address: HIDALGO
Latitude: 26.3530256
Longitude: -98.216445
---------
Address: STARR
Latitude: 26.5630409
Longitude: -98.7479897
---------
Address: WILLACY
Latitude: 26.4553947
Longitude: -97.5947484
---------
Address: ARMSTRONG
Latitude: 34.9295608
Longitude: -101.3449139
---------
Address: BRISCOE
Latitude: 34.4795161
Longitude: -101.1875029
---------
Address: CARSON
Latitude: 35.3636563
Longitude: -101.3353895
---------
Address: CASTRO
Latitude: 34.4952536
Longitude: -102.2592314
---------
Address: DALLAM
Latitude: 36.3127064
Longitude: -102.616685
---------
Address: DEAF SMITH
Latitude: 34.9323974
Longitude: -102.5983118
---------
Address: FLOYD
Latitude: 34.0266015
Longitude: -101.2765537
---------
Address: GRAY
Latitude: 35.3711816
Longitude: -100.7892236
---------
Address: HALE
Latitude: 34.0321298
Longitude: -101.8088827
---------
Address: HANSFORD
Latitude: 36.2563401
Longitude: -101.3621472
---------
Address: HARTLEY
Latitude: 35.8418438
Longitude: -102.6145811
---------
Address: HEMPHILL
Latitude: 35.8293476
Longitude: -100.2564532
---------
Address: HUTCHINSON
Latitude: 35.8148236
Longitude: -101.34844
---------
Address: LIPSCOMB
Latitude: 36.2695629
Longitude: -100.2711772
---------
Address: MOORE
Latitude: 35.8156121
Longitude: -101.9104355
---------
Address: OCHILTREE
Latitude: 36.2559217
Longitude: -100.8138152
---------
Address: OLDHAM
Latitude: 35.3907651
Longitude: -102.6193428
---------
Address: PARMER
Latitude: 34.4901153
Longitude: -102.768021
---------
Address: POTTER
Latitude: 35.3683354
Longitude: -101.8776577
---------
Address: RANDALL
Latitude: 34.9444713
Longitude: -101.8850309
---------
Address: ROBERTS
Latitude: 35.8309752
Longitude: -100.8058034
---------
Address: SHERMAN
Latitude: 36.2452294
Longitude: -101.8858689
---------
Address: SWISHER
Latitude: 34.47235
Longitude: -101.7119955
---------
Address: BORDEN
Latitude: 32.6879416
Longitude: -101.425711
---------
Address: CHILDRESS
Latitude: 34.519656850000004
Longitude: -100.20676557187427
---------
Address: COLLINGSWORTH
Latitude: 34.9487017
Longitude: -100.2669137
---------
Address: COTTLE
Latitude: 34.0573118
Longitude: -100.283259
---------
Address: DICKENS
Latitude: 33.6170056
Longitude: -100.7614115
---------
Address: DONLEY
Latitude: 34.9315007
Longitude: -100.8145306
---------
Address: FOARD
Latitude: 33.9502317
Longitude: -99.7310158
---------
Address: GARZA
Latitude: 33.1414018
Longitude: -101.287742
---------

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=HALL%2CTexas&format=json&limit=1

Address: HALL
Latitude: 34.5036637
Longitude: -100.6536777
---------
Address: HARDEMAN
Latitude: 34.2510707
Longitude: -99.7322571
---------
Address: KENT
Latitude: 33.1665316
Longitude: -100.7846477
---------
Address: KING
Latitude: 33.588178
Longitude: -100.2178972
---------
Address: MOTLEY
Latitude: 34.0395459
Longitude: -100.7744062
---------
Address: WHEELER
Latitude: 35.3921902
Longitude: -100.2632764
---------
Address: WICHITA
Latitude: 33.9516534
Longitude: -98.7088886
---------
Address: WILBARGER
Latitude: 34.0265157
Longitude: -99.2085961
---------
Address: AUSTIN
Latitude: 30.2711286
Longitude: -97.7436995
---------
Address: BEE
Latitude: 28.3871179
Longitude: -97.7191838
---------
Address: BEXAR
Latitude: 29.4263987
Longitude: -98.5104781
---------
Address: BURLESON
Latitude: 30.4764878
Longitude: -96.6353488
---------
Address: CALDWELL
Latitude: 29.8298971
Longitude: -97.5959641
---------
Address: COLORADO
Latitude: 29.6099609
Longitude: -96.5478826
---------
Address: FAYETTE
Latitude: 29.8381635
Longitude: -96.9559692
---------
Address: GOLIAD
Latitude: 28.6467776
Longitude: -97.4379552
---------
Address: GONZALES
Latitude: 29.4436555
Longitude: -97.5108636
---------
Address: GUADALUPE
Latitude: 29.6480061
Longitude: -97.8279576
---------
Address: HAYS
Latitude: 30.0447901
Longitude: -98.0393127
---------
Address: KARNES
Latitude: 28.8791858
Longitude: -97.9062893
---------
Address: MEDINA
Latitude: 29.2836281
Longitude: -99.1126826
---------
Address: TRAVIS
Latitude: 30.2878569
Longitude: -97.7561392
---------
Address: WASHINGTON
Latitude: 30.2226352
Longitude: -96.3936114
---------
Address: WILSON
Latitude: 29.1589961
Longitude: -98.1251465
---------
Address: ATASCOSA
Latitude: 28.8554434
Longitude: -98.5316314
---------
Address: DIMMIT
Latitude: 28.3821949
Longitude: -99.7178226
---------
Address: FRIO
Latitude: 28.8352831
Longitude: -99.1226618
---------
Address: JIM WELLS
Latitude: 27.8067733
Longitude: -98.1084601
---------
Address: LIVE OAK
Latitude: 28.2678746
Longitude: -98.101923
---------
Address: ZAPATA
Latitude: 26.9879626
Longitude: -99.1673556
---------
Address: ZAVALA
Latitude: 28.8366612
Longitude: -99.767631
---------
Address: ANDREWS
Latitude: 32.2690953
Longitude: -102.6042447
---------
Address: BAILEY
Latitude: 34.0349194
Longitude: -102.8149372
---------
Address: COCHRAN
Latitude: 33.5905096
Longitude: -102.805677
---------
Address: CROSBY
Latitude: 33.5778818
Longitude: -101.2855737
---------
Address: DAWSON
Latitude: 32.7410762
Longitude: -101.9576048
---------
Address: GAINES
Latitude: 32.7044935
Longitude: -102.6220553
---------
Address: GLASSCOCK
Latitude: 31.8640224
Longitude: -101.4811312
---------
Address: HOCKLEY
Latitude: 33.5714311
Longitude: -102.3110415
---------
Address: HOWARD
Latitude: 32.3047833
Longitude: -101.4271085
---------
Address: LAMB
Latitude: 34.0321667
Longitude: -102.3429233
---------
Address: LUBBOCK
Latitude: 33.5634402
Longitude: -101.8792389
---------
Address: LYNN
Latitude: 33.1474257
Longitude: -101.812592
---------
Address: MARTIN
Latitude: 32.2675039
Longitude: -101.9190317
---------
Address: MIDLAND
Latitude: 31.83688
Longitude: -102.0103767
---------
Address: TERRY
Latitude: 33.1514254
Longitude: -102.3328121
---------
Address: YOAKUM
Latitude: 33.1536951
Longitude: -102.833579
---------
Address: BAYLOR
Latitude: 33.574962
Longitude: -99.2000611
---------
Address: COLEMAN
Latitude: 31.7766863
Longitude: -99.4461098
---------
Address: FISHER
Latitude: 32.7090882
Longitude: -100.3811922
---------
Address: HASKELL
Latitude: 33.1542164
Longitude: -99.7199972
---------
Address: JONES
Latitude: 32.7135946
Longitude: -99.8606106
---------
Address: KNOX
Latitude: 33.5871385
Longitude: -99.7073621
---------
Address: MITCHELL
Latitude: 32.2898049
Longitude: -100.9213003
---------
Address: NOLAN
Latitude: 32.2719306
Longitude: -100.3987748
---------
Address: RUNNELS
Latitude: 31.8282551
Longitude: -99.9779922
---------
Address: SCURRY
Latitude: 32.7225172
Longitude: -100.9052015
---------
Address: STONEWALL
Latitude: 33.1571742
Longitude: -100.2453011
---------
Address: TAYLOR
Latitude: 32.2793121
Longitude: -99.8812612
---------
Address: BREWSTER
Latitude: 29.8462742
Longitude: -103.2400734
---------
Address: EL PASO
Latitude: 31.7550511
Longitude: -106.4882345
---------
Address: HUDSPETH
Latitude: 31.5388627
Longitude: -105.4752945
---------
Address: PECOS
Latitude: 30.7857437
Longitude: -102.8065415
---------
Address: REEVES
Latitude: 31.232003
Longitude: -103.6583657
---------
Address: BRAZORIA
Latitude: 29.18161
Longitude: -95.4993375
---------
Address: CALHOUN
Latitude: 28.5031572
Longitude: -96.6736551
---------
Address: FORT BEND
Latitude: 29.511218
Longitude: -95.7807348
---------
Address: HARRIS
Latitude: 29.8119769
Longitude: -95.3741247
---------
Address: JACKSON
Latitude: 28.9224028
Longitude: -96.55561
---------
Address: MATAGORDA
Latitude: 28.8879823
Longitude: -96.0035095
---------
Address: VICTORIA
Latitude: 28.8026443
Longitude: -96.9766308
---------
Address: WHARTON
Latitude: 29.2454534
Longitude: -96.2291474
---------
Address: DALLAS
Latitude: 32.7762719
Longitude: -96.7968559
---------
Address: TARRANT
Latitude: 32.7513658
Longitude: -97.335696
---------
Address: MILLS
Latitude: 31.4861082
Longitude: -98.5527272
---------
Address: CASS
Latitude: 33.0560857
Longitude: -94.3510366
---------
Address: HENDERSON
Latitude: 32.182598
Longitude: -95.7893178
---------
Address: NACOGDOCHES
Latitude: 31.5970503
Longitude: -94.5927451
---------
Address: PANOLA
Latitude: 32.1367712
Longitude: -94.3130073
---------
Address: RED RIVER
Latitude: 33.571979
Longitude: -95.0429674
---------
Address: RUSK
Latitude: 32.051377
Longitude: -94.7906553
---------
Address: SHELBY
Latitude: 31.7716364
Longitude: -94.1301652
---------
Address: SMITH
Latitude: 32.3402898
Longitude: -95.2563971
---------
Address: TITUS
Latitude: 33.2040399
Longitude: -94.9651725
---------
Address: WOOD
Latitude: 32.7577475
Longitude: -95.3812941
---------
Address: HARDIN
Latitude: 30.3049642
Longitude: -94.403904
---------
Address: JASPER
Latitude: 30.7485258
Longitude: -94.000884
---------
Address: LEON
Latitude: 31.2715127
Longitude: -95.9953382
---------
Address: MONTGOMERY
Latitude: 30.301949
Longitude: -95.5065944
---------
Address: NEWTON
Latitude: 30.8118989
Longitude: -93.740504
---------
Address: POLK
Latitude: 30.7642828
Longitude: -94.8192175
---------
Address: SABINE
Latitude: 31.3325489
Longitude: -93.8722218
---------
Address: SAN AUGUSTINE
Latitude: 31.3970365
Longitude: -94.1751389
---------
Address: TRINITY
Latitude: 31.0834452
Longitude: -95.1219348
---------
Address: EDWARDS
Latitude: 29.9116617
Longitude: -100.3457636
---------
Address: GILLESPIE
Latitude: 30.2954086
Longitude: -98.9086643
---------
Address: KENDALL
Latitude: 29.943885
Longitude: -98.7258845
---------
Address: BASTROP
Latitude: 30.0541116
Longitude: -97.3887764
---------
Address: COMAL
Latitude: 29.7979704
Longitude: -98.2690787
---------
Address: LAVACA
Latitude: 29.3703333
Longitude: -96.9334531
---------
Address: LEE
Latitude: 30.3031353
Longitude: -96.9588587
---------
Address: LA SALLE
Latitude: 28.3391148
Longitude: -99.0982257
---------
Address: MCMULLEN
Latitude: 28.3138785
Longitude: -98.5527241
---------
Address: CHAMBERS
Latitude: 29.7191125
Longitude: -94.5412295
---------
Address: LIBERTY
Latitude: 30.0856736
Longitude: -94.7856262
---------
Address: ORANGE
Latitude: 30.1228634
Longitude: -93.9041169
---------
Address: MONTAGUE
Latitude: 33.6205753
Longitude: -97.7215754
---------
Address: STEPHENS
Latitude: 32.6944793
Longitude: -98.8200722
---------
Address: DUVAL
Latitude: 27.6708701
Longitude: -98.5121975
---------
Address: JEFFERSON
Latitude: 29.834772
Longitude: -94.1704496
---------
Address: ARANSAS
Latitude: 28.1987876
Longitude: -96.947708
---------
Address: HOOD
Latitude: 32.4107555
Longitude: -97.828282
---------
Address: JACK
Latitude: 33.2127019
Longitude: -98.1639199
---------
Address: PALO PINTO
Latitude: 32.7215726
Longitude: -98.2814881
---------
Address: SOMERVELL
Latitude: 32.2275813
Longitude: -97.7724138
---------
Address: CAMP
Latitude: 32.9723128
Longitude: -94.9852858
---------
Address: CHEROKEE
Latitude: 31.8390826
Longitude: -95.1791849
---------
Address: GREGG
Latitude: 32.4492408
Longitude: -94.8532848
---------
Address: MARION
Latitude: 32.7931661
Longitude: -94.344488
---------
Address: MORRIS
Latitude: 33.0738633
Longitude: -94.7392197
---------
Address: RAINS
Latitude: 32.8685085
Longitude: -95.7964017
---------
Address: UPSHUR
Latitude: 32.7263725
Longitude: -94.9286251
---------
Address: VAN ZANDT
Latitude: 32.5375642
Longitude: -95.8292165
---------
Address: ANGELINA
Latitude: 31.2544545
Longitude: -94.6181177
---------
Address: TYLER
Latitude: 30.7563939
Longitude: -94.3984613
---------
Address: BANDERA
Latitude: 29.7643475
Longitude: -99.234526
---------
Address: CROCKETT
Latitude: 30.6517377
Longitude: -101.3766686
---------
Address: KERR
Latitude: 30.045717
Longitude: -99.3884839
---------
Address: KIMBLE
Latitude: 30.4744131
Longitude: -99.8199792
---------
Address: LAMPASAS
Latitude: 31.1761363
Longitude: -98.240563
---------
Address: MASON
Latitude: 30.705029
Longitude: -99.2233284
---------
Address: MENARD
Latitude: 30.8573562
Longitude: -99.8320637
---------
Address: REAL
Latitude: 29.7949383
Longitude: -99.8280905
---------
Address: STERLING
Latitude: 31.8151416
Longitude: -101.0452671
---------
Address: SUTTON
Latitude: 30.51216325
Longitude: -100.53841807826248
---------
Address: VAL VERDE
Latitude: 29.9153286
Longitude: -101.1284631
---------
Address: BROOKS
Latitude: 26.9879856
Longitude: -98.2071041
---------
Address: JIM HOGG
Latitude: 27.0065425
Longitude: -98.7047316
---------
Address: KENEDY
Latitude: 26.9205171
Longitude: -97.7461361
---------
Address: MAVERICK
Latitude: 28.792861
Longitude: -100.3110817
---------
Address: WEBB
Latitude: 27.6983621
Longitude: -99.2523577
---------
Address: CRANE
Latitude: 31.4486118
Longitude: -102.5163544
---------
Address: CULBERSON
Latitude: 31.4622625
Longitude: -104.482834
---------
Address: ECTOR
Latitude: 31.8941755
Longitude: -102.5794339
---------
Address: JEFF DAVIS
Latitude: 30.7018281
Longitude: -104.1501698
---------
Address: LOVING
Latitude: 31.8364044
Longitude: -103.5663536
---------
Address: PRESIDIO
Latitude: 29.9883766
Longitude: -104.233655
---------
Address: TERRELL
Latitude: 30.1990738
Longitude: -102.0974881
---------
Address: WARD
Latitude: 31.5007583
Longitude: -103.0781186
---------
Address: WINKLER
Latitude: 31.8005913
Longitude: -103.0762299
---------
Address: GALVESTON
Latitude: 29.3872254
Longitude: -94.992736
---------

In [29]:
df_geolocation.head(3)

   County   Latitude  Longitude
0    BELL  31.008166 -97.431441
1  BOSQUE  31.877836 -97.656101
2  COLLIN  33.160963 -96.606098

In [30]:
import folium

# Create a Folium map centered on the US
map_us = folium.Map(location=[39.8283, -98.5795], zoom_start=4)

# Iterate over each row in the DataFrame
for index, row in df_geolocation.iterrows():
    address = row['County']
    latitude = row['Latitude']
    longitude = row['Longitude']
    
    # Add a marker for each location
    folium.Marker(location=[latitude, longitude], popup=address).add_to(map_us)

# Display the map
map_us

In [31]:
df_combined = pd.merge(df_combined, 
                       df_geolocation, 
                       on = ['County'],
                       how = 'inner')
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",(D),(D),"37,000",90.9574,31.008166,-97.431441
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00","23,500",NaN,"52,000",89.0778,31.877836,-97.656101
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00","17,400",NaN,"42,000",104.1654,33.160963,-96.606098
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,"3,002.00","4,870.00",(D),(D),"86,000",93.7260,33.582486,-97.205530
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,"1,657.00","4,705.00","25,500",NaN,"55,000",84.9122,31.368933,-97.818408

In [32]:
columns_list = list(df_combined.columns)
df_combined = df_combined[columns_list].replace(['(D) ',' (D)'], np.nan, regex=False)

In [33]:
# however the values are still in string format- convert them to float
df_combined['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>'] = df_combined['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>'].str.replace(',', '').astype(float)

In [36]:
df_combined['CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>'] = df_combined['CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>'].str.replace(',', '').astype(float)
df_combined['CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>'] = df_combined['CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>'].str.replace(',', '').astype(float)

In [37]:
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",NaN,NaN,37000.0,90.9574,31.008166,-97.431441
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00",23500.0,NaN,52000.0,89.0778,31.877836,-97.656101
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00",17400.0,NaN,42000.0,104.1654,33.160963,-96.606098
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,"3,002.00","4,870.00",NaN,NaN,86000.0,93.7260,33.582486,-97.205530
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,"1,657.00","4,705.00",25500.0,NaN,55000.0,84.9122,31.368933,-97.818408

# METHANE EMISSION FROM THE CATTLE

In [38]:
# Define the multiplication factor
multiplication_factor = 118  # kg/head/year    ## IPCC EF DATASET

# Check if the 'cattle' column is not empty
df_combined['CH4-Kg/year-milk'] = df_combined['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>'].apply(lambda x: x * multiplication_factor if pd.notnull(x) else x)

# Print the new DataFrame
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00",23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00",17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN

In [39]:
df_combined.columns

Index(['Geo Level', 'State', 'State ANSI', 'Ag District', 'Ag District Code',
       'County', 'County ANSI', 'COTTON-AREA-ACRES', 'CORN-GRAIN-ACRES',
       'SORGHUM-ACRES', 'CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>',
       'Mean Annual\nPrecipitation (cm.)', 'Latitude', 'Longitude',
       'CH4-Kg/year-milk'],
      dtype='object')

In [40]:
# Define the multiplication factor
multiplication_factor = 47  # kg/head/year

# Check if the 'cattle' column is not empty
df_combined['CH4-Kg/year-non-milk'] = df_combined['CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>'].apply(lambda x: x * multiplication_factor if pd.notnull(x) else x)

# Print the new DataFrame
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00",23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00",17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,"3,002.00","4,870.00",NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,"1,657.00","4,705.00",25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0

In [41]:
# Define the multiplication factor
multiplication_factor = 47  # kg/head/year

# Check if the 'cattle' column is not empty
df_combined['CH4-Kg/year-calves'] = df_combined['CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>'].apply(lambda x: x * multiplication_factor if pd.notnull(x) else x)

# Print the new DataFrame
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,"6,261.00","67,409.00","7,264.00",NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,"6,243.00","3,965.00","1,299.00",23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.00,"22,840.00","7,102.00",17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0

In [43]:
columns_list = list(df_combined.columns)
columns_list

['Geo Level',
 'State',
 'State ANSI',
 'Ag District',
 'Ag District Code',
 'County',
 'County ANSI',
 'COTTON-AREA-ACRES',
 'CORN-GRAIN-ACRES',
 'SORGHUM-ACRES',
 'CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>',
 'CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',
 'CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>',
 'Mean Annual\nPrecipitation (cm.)',
 'Latitude',
 'Longitude',
 'CH4-Kg/year-milk',
 'CH4-Kg/year-non-milk',
 'CH4-Kg/year-calves']

In [44]:
df_combined['Ag District'].unique()

array(['BLACKLANDS', 'COASTAL BEND', 'CROSS TIMBERS', 'EAST TEXAS NORTH',
       'EAST TEXAS SOUTH', 'EDWARDS PLATEAU', 'LOWER VALLEY',
       'NORTHERN HIGH PLAINS', 'NORTHERN LOW PLAINS', 'SOUTH CENTRAL',
       'SOUTH TEXAS', 'SOUTHERN HIGH PLAINS', 'SOUTHERN LOW PLAINS',
       'TRANS-PECOS', 'UPPER COAST'], dtype=object)

Gas	| CO2-e |
----| ------|
CO2	| 1 |
CH4	| 28 |
N2O	| 265 |
CF4	|6,630|
C2F6|	12,200|
SF6|	22,800|
NF3|	17,200|
	
Gas|	Conversion Factor|
---|-------------------|
CO2|	3.67|
CH4|	1.33|
N2O|	1.57|
Nox|	3.29|
CO|	2.33|
CO2 Lime|	3.67|
NMVOC|	1.17|

* Region 1: 0.55
* Region 2: 0.5
* Region 3: 0.45
* Region 4: 0.45
* Region 5: 0.4
* Region 6 :0.4

#### This is categorized based on precipitation pattern. Correlation between precipitation-soil-Vegetation-[temperature] to some extent

### To reduce the multicollinearity we can consider only one factor!!

In [45]:
def calculate_application_factor(rainfall):
    if rainfall > 200:
      return 0.55 # this factors are for hectares of land
    elif 150 <= rainfall <= 200:
      return 0.5
    elif 100 <= rainfall < 150:
      return 0.45
    elif 50 <= rainfall < 100:
      return 0.4
    elif 25 <= rainfall < 50:
      return 0.4
    else:
        return 0.35

In [46]:
df_combined.columns

Index(['Geo Level', 'State', 'State ANSI', 'Ag District', 'Ag District Code',
       'County', 'County ANSI', 'COTTON-AREA-ACRES', 'CORN-GRAIN-ACRES',
       'SORGHUM-ACRES', 'CATTLE, COWS, BEEF - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',
       'CATTLE, INCL CALVES - INVENTORY  -  <b>VALUE</b>',
       'Mean Annual\nPrecipitation (cm.)', 'Latitude', 'Longitude',
       'CH4-Kg/year-milk', 'CH4-Kg/year-non-milk', 'CH4-Kg/year-calves'],
      dtype='object')

In [47]:
df_combined['COTTON-AREA-ACRES']

0      6,261.00
1      6,243.00
2        840.00
3           NaN
4           NaN
         ...
248         NaN
249         NaN
250         NaN
251         NaN
252         NaN
Name: COTTON-AREA-ACRES, Length: 253, dtype: object

In [54]:
# convert the df colum cotton area acres into float for further calculation purpose
df_combined['COTTON-AREA-ACRES'] = df_combined['COTTON-AREA-ACRES'].str.replace(',', '').astype(float)
df_combined['CORN-GRAIN-ACRES'] = df_combined['CORN-GRAIN-ACRES'].str.replace(',', '').astype(float)
df_combined['SORGHUM-ACRES'] = df_combined['SORGHUM-ACRES'].str.replace(',', '').astype(float)

In [55]:
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708

In [56]:
# Create a new column 'Application Factor' in the DataFrame
df_combined['Application Factor'] = df_combined['Mean Annual\nPrecipitation (cm.)'].apply(calculate_application_factor)

# Multiply the 'Area' column with the 'Application Factor'
df_combined['Lime-cotton-tonnes'] = df_combined['COTTON-AREA-ACRES'] * df_combined['Application Factor'] * 0.404686
df_combined['Lime-corn-tonnes'] = df_combined['CORN-GRAIN-ACRES'] * df_combined['Application Factor'] * 0.404686
df_combined['Lime-sorghum-tonnes'] = df_combined['SORGHUM-ACRES'] * df_combined['Application Factor'] * 0.404686

In [57]:
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987

E = ((M x FracLime x P X EF) + (M x (1-FracLime) x P x EF)) x Cg/1000

In [58]:
FracLime = 1
P = 0.9 # PURITY OF LIMESTONE
EF = 0.12 # EMISSION FACTOR FOR LIMESTONE
Cg = 3.67

# Calculate the 'E' column:
df_combined['E-cotton-CO2'] = ((df_combined['Lime-cotton-tonnes'] * FracLime * P * EF) + (df_combined['Lime-cotton-tonnes'] * (1 - FracLime) * P * EF)) * Cg
df_combined['E-corn-CO2'] = ((df_combined['Lime-corn-tonnes'] * FracLime * P * EF) + (df_combined['Lime-corn-tonnes'] * (1 - FracLime) * P * EF)) * Cg
df_combined['E-sorghum-CO2'] = ((df_combined['Lime-sorghum-tonnes'] * FracLime * P * EF) + (df_combined['Lime-sorghum-tonnes'] * (1 - FracLime) * P * EF)) * Cg

# Display the updated DataFrame
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652

# UREA

## COTTON

In [59]:
# Conversion factor: 1 Ha = 2.47105 acres
conversion_factor = 2.47105

# Convert urea application rate from kg/Ha to kg/acre
df_combined['Urea_tonne_cotton'] = (df_combined['COTTON-AREA-ACRES'] * 270 * 0.001) / conversion_factor 

# Display the DataFrame
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,3002.0,4870.0,NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN,4042000.0,0.40,NaN,NaN,485.946949,788.328328,192.609933,312.461816,NaN
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,1657.0,4705.0,25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0,2585000.0,0.40,NaN,NaN,268.225881,761.619052,106.314010,301.875327,NaN

In [61]:
EF = 0.20
C = 3.67

df_combined['E-cotton-urea-CO2'] = df_combined['Urea_tonne_cotton'] * EF * C
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,3002.0,4870.0,NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN,4042000.0,0.40,NaN,NaN,485.946949,788.328328,192.609933,312.461816,NaN,NaN
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,1657.0,4705.0,25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0,2585000.0,0.40,NaN,NaN,268.225881,761.619052,106.314010,301.875327,NaN,NaN

Urea application for CORN:

150 pounds * 0.453592 = kg/acre

https://www.derthickscornmaze.com/interesting-about-corn/how-much-urea-per-acre-for-corn.html

In [62]:
urea_per_acre = 150 * 0.453592 * 0.001 #tonnes per acre

df_combined['Urea_tonne_corn'] = df_combined['CORN-GRAIN-ACRES'] * urea_per_acre
df_combined.head(3)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192

In [63]:
EF = 0.20
C = 3.67

df_combined['E-corn-urea-CO2'] = df_combined['Urea_tonne_corn'] * EF * C
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn,E-corn-urea-CO2
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469,3366.437762
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842,198.014000
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192,1140.640545
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,3002.0,4870.0,NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN,4042000.0,0.40,NaN,NaN,485.946949,788.328328,192.609933,312.461816,NaN,NaN,204.252478,149.921319
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,1657.0,4705.0,25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0,2585000.0,0.40,NaN,NaN,268.225881,761.619052,106.314010,301.875327,NaN,NaN,112.740292,82.751374

According to the sources, the recommended urea rate for sorghum in the US is 4.535924 Kg per acre when conditions are moist and 9.071847 pounds per acre when conditions are dry

In [67]:
threshold = 100  # Set desired threshold value. 
factor_above_threshold = 4.5359 * 0.001 # if precipitation is above the threshold
factor_below_threshold = 9.071847 * 0.001 # if precipitation is below or equal to the threshold

df_combined['Urea_tonne_sorghum'] = np.where(df_combined['Mean Annual\nPrecipitation (cm.)'] > threshold, df_combined['SORGHUM-ACRES'] * factor_above_threshold, df_combined['SORGHUM-ACRES'] * factor_below_threshold)

In [68]:
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn,E-corn-urea-CO2,Urea_tonne_sorghum
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469,3366.437762,65.897897
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842,198.014000,11.784329
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192,1140.640545,32.213962
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,3002.0,4870.0,NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN,4042000.0,0.40,NaN,NaN,485.946949,788.328328,192.609933,312.461816,NaN,NaN,204.252478,149.921319,44.179895
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,1657.0,4705.0,25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0,2585000.0,0.40,NaN,NaN,268.225881,761.619052,106.314010,301.875327,NaN,NaN,112.740292,82.751374,42.683040

In [69]:
EF = 0.20
C = 3.67

df_combined['E-sorghum-urea-CO2'] = df_combined['Urea_tonne_sorghum'] * EF * C
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn,E-corn-urea-CO2,Urea_tonne_sorghum,E-sorghum-urea-CO2
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,NaN,NaN,37000.0,90.9574,31.008166,-97.431441,NaN,NaN,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469,3366.437762,65.897897,48.369056
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,NaN,52000.0,89.0778,31.877836,-97.656101,NaN,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842,198.014000,11.784329,8.649698
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,NaN,42000.0,104.1654,33.160963,-96.606098,NaN,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192,1140.640545,32.213962,23.645048
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,NaN,3002.0,4870.0,NaN,NaN,86000.0,93.7260,33.582486,-97.205530,NaN,NaN,4042000.0,0.40,NaN,NaN,485.946949,788.328328,192.609933,312.461816,NaN,NaN,204.252478,149.921319,44.179895,32.428043
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,NaN,1657.0,4705.0,25500.0,NaN,55000.0,84.9122,31.368933,-97.818408,NaN,1198500.0,2585000.0,0.40,NaN,NaN,268.225881,761.619052,106.314010,301.875327,NaN,NaN,112.740292,82.751374,42.683040,31.329351

In [72]:
# replace all the NaN values with zero

df_combined = df_combined.fillna(0)
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn,E-corn-urea-CO2,Urea_tonne_sorghum,E-sorghum-urea-CO2,CH4-total
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,0.0,0.0,37000.0,90.9574,31.008166,-97.431441,0.0,0.0,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469,3366.437762,65.897897,48.369056,0.0
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,0.0,52000.0,89.0778,31.877836,-97.656101,0.0,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842,198.014000,11.784329,8.649698,0.0
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,0.0,42000.0,104.1654,33.160963,-96.606098,0.0,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192,1140.640545,32.213962,23.645048,0.0
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,0.0,3002.0,4870.0,0.0,0.0,86000.0,93.7260,33.582486,-97.205530,0.0,0.0,4042000.0,0.40,0.000000,0.000000,485.946949,788.328328,192.609933,312.461816,0.000000,0.000000,204.252478,149.921319,44.179895,32.428043,0.0
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,0.0,1657.0,4705.0,25500.0,0.0,55000.0,84.9122,31.368933,-97.818408,0.0,1198500.0,2585000.0,0.40,0.000000,0.000000,268.225881,761.619052,106.314010,301.875327,0.000000,0.000000,112.740292,82.751374,42.683040,31.329351,0.0

In [76]:
df_combined['E-CH4-total-tonne'] = (df_combined['CH4-Kg/year-milk'] + df_combined['CH4-Kg/year-non-milk'] + df_combined['CH4-Kg/year-calves']) * 0.001
df_combined.head(5)

,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,COTTON-AREA-ACRES,CORN-GRAIN-ACRES,SORGHUM-ACRES,"CATTLE, COWS, BEEF - INVENTORY - <b>VALUE</b>","CATTLE, COWS, MILK - INVENTORY - <b>VALUE</b>","CATTLE, INCL CALVES - INVENTORY - <b>VALUE</b>",Mean Annual\nPrecipitation (cm.),Latitude,Longitude,CH4-Kg/year-milk,CH4-Kg/year-non-milk,CH4-Kg/year-calves,Application Factor,Lime-cotton-tonnes,E-cotton-CO2,Lime-corn-tonnes,Lime-sorghum-tonnes,E-corn-CO2,E-sorghum-CO2,Urea_tonne_cotton,E-cotton-urea-CO2,Urea_tonne_corn,E-corn-urea-CO2,Urea_tonne_sorghum,E-sorghum-urea-CO2,CH4-total,CH4-total-tonne,E-CH4-total-tonne
0,COUNTY,TEXAS,48,BLACKLANDS,40,BELL,27.0,6261.0,67409.0,7264.0,0.0,0.0,37000.0,90.9574,31.008166,-97.431441,0.0,0.0,1739000.0,0.40,1013.495618,401.709123,10911.791430,1175.855642,4324.997651,466.062142,684.109994,502.136735,4586.427469,3366.437762,65.897897,48.369056,1739000.0,1739.0,1739.0
1,COUNTY,TEXAS,48,BLACKLANDS,40,BOSQUE,35.0,6243.0,3965.0,1299.0,23500.0,0.0,52000.0,89.0778,31.877836,-97.656101,0.0,1104500.0,2444000.0,0.40,1010.581879,400.554234,641.831996,210.274846,254.396530,83.344538,682.143218,500.693122,269.773842,198.014000,11.784329,8.649698,3548500.0,3548.5,3548.5
2,COUNTY,TEXAS,48,BLACKLANDS,40,COLLIN,85.0,840.0,22840.0,7102.0,17400.0,0.0,42000.0,104.1654,33.160963,-96.606098,0.0,817800.0,1974000.0,0.45,152.971308,60.631708,4159.362708,1293.335987,1648.605003,512.626652,91.782845,67.368608,1554.006192,1140.640545,32.213962,23.645048,2791800.0,2791.8,2791.8
3,COUNTY,TEXAS,48,BLACKLANDS,40,COOKE,97.0,0.0,3002.0,4870.0,0.0,0.0,86000.0,93.7260,33.582486,-97.205530,0.0,0.0,4042000.0,0.40,0.000000,0.000000,485.946949,788.328328,192.609933,312.461816,0.000000,0.000000,204.252478,149.921319,44.179895,32.428043,4042000.0,4042.0,4042.0
4,COUNTY,TEXAS,48,BLACKLANDS,40,CORYELL,99.0,0.0,1657.0,4705.0,25500.0,0.0,55000.0,84.9122,31.368933,-97.818408,0.0,1198500.0,2585000.0,0.40,0.000000,0.000000,268.225881,761.619052,106.314010,301.875327,0.000000,0.000000,112.740292,82.751374,42.683040,31.329351,3783500.0,3783.5,3783.5

In [80]:
# N2O emissions

In [81]:
## Managment Practices
'''1. Conventional Tillage
2. Reduced Tillage
3. NoTill
'''

'1. Conventional Tillage\n2. Reduced Tillage\n3. NoTill\n'